### ISSUE TITLE
Running binary throws TypeError: y is not a function

### ISSUE THREAD

**Issue by bradfrosty** [ai/dual-publish#27]
Running the `dual-publish` binary causes the following error:

```sh
 ERROR  TypeError: y is not a function
    at showHelp (file://<path-to>/node_modules/dual-publish/show-help.js:15:12)
    at file://<path-to>/node_modules/dual-publish/bin.js:14:5
    at cli (file://<path-to>/node_modules/dual-publish/cli.js:13:11)
    at file://<path-to>/node_modules/dual-publish/bin.js:12:1
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

Looks like it's from the replacement of `nanocolors` with `picocolors`. 
`picocolors` does not contain a function `y` on the [exported object](https://github.com/alexeyraspopov/picocolors#usage).

**Comment by ai** [comment]
Thanks. Fixed 03e50a2

**Comment by ai** [comment]
Ths fix was released in 2.0.2.
